"""Duck-typed protocols for keyboard and mouse backends."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class KeyboardBackend(Protocol):
    name: str

    def type_char(self, ch: str) -> None: ...

    def backspace(self) -> None: ...

    def enter(self) -> None: ...

    def tab(self) -> None: ...

    def key(self, name: str) -> None: ...

    def hotkey(self, *keys: str) -> None: ...

    def close(self) -> None: ...


@runtime_checkable
class MouseBackend(Protocol):
    name: str

    def get_position(self) -> tuple[float, float]: ...

    def human_move(self, start, end, target_width=60.0, stop_event=None) -> None: ...

    def press_button(self) -> None: ...

    def release_button(self) -> None: ...

    def click(self) -> None: ...

    def close(self) -> None: ...
